services:
  postgres:
    image: postgres:${AYON_STACK_POSTGRES_TAG:-15}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ayon"]
      interval: 5s
      timeout: 5s
      retries: 5

    expose: [5432]

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "db:/var/lib/postgresql/data"

    environment:
      - "POSTGRES_USER=ayon"
      - "POSTGRES_PASSWORD=ayon"
      - "POSTGRES_DB=ayon"

  keycloak-db:
    image: postgres:15
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5
    expose: [5432]
    volumes:
      - "keycloak_db:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=keycloak"
      - "POSTGRES_PASSWORD=keycloak"
      - "POSTGRES_DB=keycloak"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start
    restart: unless-stopped
    depends_on:
      keycloak-db:
        condition: service_healthy
    expose: [8080]
    ports:
      - "8082:8080"
    environment:
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
      - "KC_DB=postgres"
      - "KC_DB_URL_HOST=keycloak-db"
      - "KC_DB_URL_DATABASE=keycloak"
      - "KC_DB_USERNAME=keycloak"
      - "KC_DB_PASSWORD=keycloak"

  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 5

    expose: [6379]


  server:
    image: ayon-self-docker
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/info"]
      interval: 10s
      timeout: 2s
      retries: 3

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

    expose: [5000]
    ports: 
      - ${AYON_STACK_SERVER_PORT:-5000}:5000

    volumes:
      - "./addons:/addons"
      - "./storage:/storage"

      # comment out the following line on Windows
      - "/etc/localtime:/etc/localtime:ro"

      # uncomment the following line if you need to work on the backend code
      - "./backend:/backend"

volumes:
  db: {}
  keycloak_db: {}
