version: "3.3"
services:
  postgres:
    image: postgres
    expose:
      - 5432
    environment:
      - "POSTGRES_USER=pypeusr"
      - "POSTGRES_PASSWORD=pypepass"
      - "POSTGRES_DB=pype"
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    expose:
      - 6379
    restart: unless-stopped

  server:
    image: ynput/ayon:latest
    restart: unless-stopped
    volumes:
      - "./addons:/addons"
      - "./backend:/backend"
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - postgres
    environment:
      - "AYON_DISCORD_CLIENT_ID=${AYON_DISCORD_CLIENT_ID-}"
      - "AYON_DISCORD_CLIENT_SECRET=${AYON_DISCORD_CLIENT_SECRET-}"
      - "AYON_GOOGLE_CLIENT_ID=${AYON_GOOGLE_CLIENT_ID-}"
      - "AYON_GOOGLE_CLIENT_SECRET=${AYON_GOOGLE_CLIENT_SECRET-}"

volumes:
  db: {}
